# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sentinel2Download
                                 A QGIS plugin
 Plugin này cho phép tải về ảnh vệ tinh Sentinel-2 theo đơn vị hành chính cấp xã
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-13
        copyright            : (C) 2020 by Nguyễn Văn Thị
        email                : nguyenvanthi@ifee.edu.vn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Sentinel2Download class from file Sentinel2Download.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sentinel2_download import Sentinel2Download
    return Sentinel2Download(iface)
